version: "4.29.0"
services:
  kong:
    image: kong:latest
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"

  eventorganizer:
    build:
      context: EventOrganizer
      dockerfile: DockerFile
    command: python manage.py runserver 0.0.0.0:8003
    ports:
      - "8003:8003"

  eventparticipant:
    build:
      context: EventParticipant
      dockerfile: DockerFile
    command: python manage.py runserver 0.0.0.0:8002
    ports:
      - "8002:8002"
  
  eventnotification:
   build:
     context: EventNotification
     dockerfile: DockerFile
   command: python manage.py runserver 0.0.0.0:8004
   ports:
     - "8004:8004" 

  eventauth:
   build:
     context: EventAuth
     dockerfile: DockerFile
   command: python manage.py runserver 0.0.0.0:8005
   ports:
     - "8005:8005" 
