# Generated by Django 4.2.13 on 2024-06-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventOrganizer', '0004_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='events', to='EventOrganizer.participant'),
        ),
    ]
