# Generated by Django 4.2.13 on 2024-06-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventOrganizer', '0005_participant_event_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.AddField(
            model_name='participant',
            name='username',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
