# Generated by Django 4.2.13 on 2024-05-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventParticipant', '0003_event_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
