# Generated by Django 4.2.13 on 2024-06-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventParticipant', '0005_userpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='app_user',
        ),
    ]
