# Generated by Django 4.2.13 on 2024-06-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventParticipant', '0008_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='events', to='EventParticipant.participant'),
        ),
    ]
