version: "4.29.0"
services:
  backend:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 127.0.0.1:8002:8002
    volumes:
      - .:/EventParticipant
  #  depends_on:
  #    - db

  # db:
  #  image: mysql:8.0.37
  #  restart: always
  #  environment:
  #    MYSQL_DATABASE: EventOrganizerEvents
  #    MYSQL_USER: root
  #    MYSQL_PASSWORD: root
  #    MYSQL_ROOT_PASSWORD: root
  #  volumes:
  #    - .dbdata:/var/lib/mysql
  #  ports:
  #    - 33066:3306


