"""
Django settings for EventParticipant project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pben@86jfl58cat@$0p)r&mmp%uxahootycktmvyv**l_!ssat'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['host.docker.internal', '127.0.0.1', '127.0.0.1:8000', 'localhost', 'eventparticipant', 'eventorganizer']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    #'django_extensions',
    'EventParticipant',
    'paypal.standard.ipn',
    # 'celery',
    # 'kombu.transport.django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EventParticipant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EventParticipant.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# RABBITMQ_CONFIG = {
#     'default': {
#         'host': 'localhost',
#         'port': 5672,
#         'user': 'guest',
#         'password': 'guest',
#     },
# }

# CELERY_BROKER_URL = BROKER_URL = 'amqp://guest:guest@localhost:5672//'
# CELERY_TASK_DEFAULT_EXCHANGE = "celery"
# CELERY_ACCEPT_CONTENT = ["json"]
# CELERY_TASK_SERIALIZER = "json"
# CELERY_TASK_QUEUES = {
#     "data_queue": {
#         "binding_key": "data_queue",
#     }
# }
# CELERY_BROKER_HEARTBEAT = 0
#
# CELERY_IMPORTS = [
#     'EventParticipant.tasks',
# ]

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


PAYPAL_RECEIVER_EMAIL = 'businesstestevent@business.example.com'
PAYPAL_TEST = True

STRIPE_SECRET_KEY_TEST = "sk_test_51PMuIN00vGjnA9OjWkJBiLdC0ZuSb3R6dmQ0hdH7qNr69G9R0buOdO5Zgu5yFWrk9Dkc2UZqCILvnsezGrAniOqU00qo83Bnb5"
STRIPE_WEBHOOK_SECRET_TEST = "whsec_46fbced2b7e03239808b20e77e71ed76207ea89a22629ca65041b7d92d51d5fe"
REDIRECT_DOMAIN = 'http://127.0.0.1:8002'

SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # Ustawienie na True w środowisku produkcyjnym
SESSION_COOKIE_SAMESITE = 'Lax'  # Lub 'Strict' w zależności od potrzeb
SESSION_COOKIE_NAME = 'sessionid'