# Generated by Django 4.2.13 on 2024-06-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventNotiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='username',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
