# Generated by Django 4.2.13 on 2024-06-14 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventNotiApp', '0002_emails_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emails',
            new_name='UsersToEmail',
        ),
    ]
