version: "4.29.0"
services:
  backend:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 8000:8000
    volumes:
      - .:/EventOrganizer
    depends_on:
      - rabbitmq  # backend zależy od RabbitMQ
    environment:
      BROKER_URL: 'amqp://guest:guest@rabbitmq:5672//'  # URL RabbitMQ dla Kombu

  rabbitmq:
    image: rabbitmq:3-management  # Użycie obrazu RabbitMQ z interfejsem zarządzania
    ports:
      - "5672:5672"  # Port RabbitMQ
      - "15672:15672"  # Port interfejsu zarządzania
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Wolumin na dane RabbitMQ

volumes:
  rabbitmq_data:

  #  depends_on:
  #    - db

  # db:
  #  image: mysql:8.0.37
  #  restart: always
  #  environment:
  #    MYSQL_DATABASE: EventOrganizerEvents
  #    MYSQL_USER: root
  #    MYSQL_PASSWORD: root
  #    MYSQL_ROOT_PASSWORD: root
  #  volumes:
  #    - .dbdata:/var/lib/mysql
  #  ports:
  #    - 33066:3306


