FROM python:3.9
ENV PYTHONUNBUFFERED 1
WORKDIR /EventOrganizer
COPY requirements.txt /EventOrganizer/requirements.txt
RUN pip install -r requirements.txt
COPY . /EventOrganizer


CMD python manage.py runserver 0.0.0.0:8000
